SURVEY_DURATION_YEARS: 6.
SURVEY_AREA_DEG2: 5000.
# pessimistic number of valid positioners
NUMBER_OF_FIBERS: 4500
# only 20 extra fibers per petal for sky because we use broken motors (TBD)
NUMBER_OF_SKY_FIBERS: 100
# 10 std stars per petal
NUMBER_OF_STAR_FIBERS: 100
# 6 mm patrol radius = 1.42 arcmin (plate scale from 107um for 1.52 arcsec)
# 10% smaller after tuning
FIBER_PATROL_AREA_DEG2: 0.0015
# 420 mm radius
FOCAL_PLANE_AREA_DEG2: 8.63
# sum of efftime_spec between May 14, 2021 and May 14, 2022 for main, darktime program
EFFECTIVE_TIME_PER_YEAR_HOURS: 700.
EFFECTIVE_TIME_PER_TILE_SECONDS: 1200.

# Max magnitude
RMAG_MAX: 24.2

# Total target density (optional, overwrites the integral of the magnitude distibution)
# TOTAL_TARGET_DENSITY: 1000

# Demographics of LBGs in the target selection sample
TARGET_FRAC_LBG_TEMPLATE_0: 0.17
TARGET_FRAC_LBG_TEMPLATE_1: 0.14
TARGET_FRAC_LBG_TEMPLATE_2: 0.14
TARGET_FRAC_LBG_TEMPLATE_3: 0.25
TARGET_FRAC_NON_LBG: 0.3 # just to check
