SURVEY_DURATION_YEARS: 5
# half of 14,000 deg2 because we consider 2 sites with the same instrument
SURVEY_AREA_DEG2: 7000.
# new focal plane
NUMBER_OF_FIBERS: 14000
# 40 fibers per petal for sky
NUMBER_OF_SKY_FIBERS: 400
# 10 std stars per petal
NUMBER_OF_STAR_FIBERS: 100
# 4 mm patrol radius, but 3.7mm effective position radius to match instrumented area
# reported in DESI-7252 slide 15, then apply plate scale from 107 um to 1.52 arcsec
FIBER_PATROL_AREA_DEG2: 0.00067
# 420 mm radius
FOCAL_PLANE_AREA_DEG2: 8.63
# sum of efftime_spec between May 14, 2021 and May 14, 2022 for main, darktime program
# 700*1.2 with reduced readnoise in CCDs
EFFECTIVE_TIME_PER_YEAR_HOURS: 840.
EFFECTIVE_TIME_PER_TILE_SECONDS: 1200.

# Max magnitude
RMAG_MAX: 24.5

# Total target density (optional, overwrites the integral of the magnitude distibution)
# TOTAL_TARGET_DENSITY: 1000

# Demographics of LBGs in the target selection sample
TARGET_FRAC_LBG_TEMPLATE_0: 0.17
TARGET_FRAC_LBG_TEMPLATE_1: 0.14
TARGET_FRAC_LBG_TEMPLATE_2: 0.14
TARGET_FRAC_LBG_TEMPLATE_3: 0.25
TARGET_FRAC_NON_LBG: 0.3 # just to check
