SURVEY_DURATION_YEARS: 5
SURVEY_AREA_DEG2: 8000.
# new focal plane
NUMBER_OF_FIBERS: 11250
# 40 fibers per petal for sky
NUMBER_OF_SKY_FIBERS: 400
# 10 std stars per petal
NUMBER_OF_STAR_FIBERS: 100
# 4 mm patrol radius ?
FIBER_PATROL_AREA_DEG2: 0.000782
# 420 mm radius
FOCAL_PLANE_AREA_DEG2: 8.63
# sum of efftime_spec between May 14, 2021 and May 14, 2022 for main, darktime program
EFFECTIVE_TIME_PER_YEAR_HOURS: 700.
EFFECTIVE_TIME_PER_TILE_SECONDS: 1200.